### ISSUE TITLE
Issues with Cinderbella and Precision Crops in 1.10.2

### ISSUE THREAD

**Issue by ate0ate** [bafomdad/uniquecrops#1]
It seems pretty clear that the precision crop should be broken at the next to last stage of growth when it is all blue, but I never get anything other than a seed when I break the crop. Same at any other stage as well, except the last stage of growth when I can get two seeds rather than just one.

The Cinderbella doesn't ever seem to grow at all nor does it ever turn into a dead bush. It just stays at 0 percent growth for days until I break it myself. I've tried pumpkins growing on all four sides at the same height as the crop, one block lower, completely surrounding the cinderbella. I've planted them at every time possible between midnight and dawn and no matter what I do it just stays at 0 percent.

This is all using forge 12.18.3.2239 and Unique Crops 0.1.52. Awesome mod BTW. Pretty different.

**Comment by bafomdad** [comment]
Hi, thank you for the bug report(s)!

I investigated the cinderbella crop problem, and it appears I left in a test condition that made the growth method do nothing, keeping it from growing naturally properly. Whoops. The bonemeal part still works, though, but it's still an issue so I'll fix it of course :]

I am unable to reproduce the problem with harvesting precision crops. I'll look at the drops code for it.

**Comment by ate0ate** [comment]
Thanks for checking it out! All of the crops seem to be working great except for the two mentioned. I'll test the precision crop under some different conditions. I am using quite a few mods so maybe something I have setup is interfering with the precision crop drops in some way.

**Comment by ate0ate** [comment]
I got the Cinderbella crop to grow with bonemeal. Is its drop supposed to just be seeds and Unique Crop Guide Books? Kind of a strange drop. I was hoping for a glass slipper:P 

I still can't get the precision crop to drop anything other than just seeds. I've moved it from my modded farm to a simple vanilla farming setup and still no luck. Doesn't matter if I use my hand to harvest or a fortune III tool. I don't know what is going on.

**Comment by bafomdad** [comment]
right, the glass slipper, lol. I found that out while I was fixing the other stuff with the crop. fixed now, no worries.

I've also attempted adding different drop behavior for the precision crop, to hopefully make it drop stuff for real, when it is at its bluest

**Comment by ate0ate** [comment]
Looking good! Thank you much for your time. The new crops are awesome, very original.

**Comment by cinniebuns** [comment]
I know this is an old thread, but there seems to be trouble with the cinderbella crop still! I am unable to grow it no matter what I do. Doesn't matter what time it is in the game, the crop won't grow. It withers away.
