### ISSUE TITLE
Startup crash with Astral Sorcery 1.9+

### ISSUE THREAD

**Issue by luke-bravenboer** [bafomdad/uniquecrops#10]
**Description**
Since the Astral Sorcery 1.9 update, mods have been crashing left, right & center, with the same cause; some exception thrown during startup, stemming from '_hellfirepvp.astralsorcery.common.enchantment.amulet.EnchantmentUpgradeHelper.isItemBlacklisted()_', but Astral Sorcery claims they're not the cause of the issue, merely the identifier:

- https://github.com/HellFirePvP/AstralSorcery/issues/762

The symptom is basically that the game just crashes during startup. The bug is preventing me from updating Astral Sorcery as long as I have Unique Crops installed.
The issue appears to be that the ItemGeneric has no limit to the amount of damage values it will operate with, and so is getting an out of bounds exception in the getUnlocalizedName() method with very high damage values:

**Log**
```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Minecraft Forge (forge)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 32767
    at com.bafomdad.uniquecrops.items.ItemGeneric.getUnlocalizedName(ItemGeneric.java:99)
    at net.minecraft.item.ItemStack.getUnlocalizedName(ItemStack.java:509)
    at com.bafomdad.uniquecrops.items.ItemGeneric.getItemStackLimit(ItemGeneric.java:331)
    at net.minecraft.item.ItemStack.getMaxStackSize(ItemStack.java:248)
    at hellfirepvp.astralsorcery.common.enchantment.amulet.EnchantmentUpgradeHelper.isItemBlacklisted(EnchantmentUpgradeHelper.java:176)
```

Full crash log here: https://paste.dimdev.org/xequfiwozo.mccrash

**Versions**
Forge: 14.23.4.2705
Unique Crops: 1.12-0.1.52
Astral Sorcery: 1.12.2-1.9.0
Baubles: 1.12-1.5.2

**Comment by luke-bravenboer** [comment]
Realised / remembered that NEI has nothing to do with this issue, so have updated the title & description accordingly.

**Comment by luke-bravenboer** [comment]
Update: [Astral Sorcery version 1.9.2](https://minecraft.curseforge.com/projects/astral-sorcery/files/2578281) fixes this issue on their end (thank god); can confirm crash is no longer occurring.
Ticket can be closed, root cause was specifically Astral Sorcery versions 1.9 & 1.9.1.

**Comment by luke-bravenboer** [comment]
Sorry for closing it prematurely, but actually... the issue doesn't occur any more with just Astral Sorcery & Unique crops installed, _however_ it can still be triggered with a third mod- so far I've seen it happen with those two + NEI, as well as Robotic Parts (the 1.12 Cyberware port).

It's pretty much the same stack trace still:
https://paste.dimdev.org/cevezineri.mccrash

Though at this point, it's probably more of an issue with the other mods (NEI & Cyberware)... at any rate, documenting my findings here.

**Comment by bafomdad** [comment]
either way, this issue is always worth looking into on my end here.

unfortunately, because I have been prioritizing this mod very far down the list of things to do, along with having focused on adding features, this may not get an attempted fix for a while.

apologies, and thank you for the report all the same!

**Comment by luke-bravenboer** [comment]
Update: Astral Sorcery [v1.9.4](https://minecraft.curseforge.com/projects/astral-sorcery/files/2591271) actually fixes the issue on their end, for real this time!

Not sure if you still want to keep this ticket open, but it should no longer be an issue now.
