### ISSUE TITLE
Cinderbella confusing behavior

### ISSUE THREAD

**Issue by lynaevm** [bafomdad/uniquecrops#14]
I'm getting some very confusing behavior from the cinderbella plant.  The documentation reads "They must be planted between midnight and dawn, while surrounded on all 4 sides by pumpkins. If it is not planted in this fashion or harvested before midnight, it withers away." but that doesn't seem to describe their behavior at all.

I seem to be able to plant them at any time EXCEPT between midnight and dawn and from what I can tell, they grow just fine without any pumpkins.   The first day they were planted, my cinderbellas turned into dead bushes  after midnight, but after replanting them and letting them grow again they didn't seem to be effected by the time passing at all.

I am very intrigued by this mod but don't know how to use it in a pack with such odd behavior.

**Comment by VasalisErretti** [comment]
I'm getting a similar type of issue, on the RAD pack, it can be planted any time except midnight to dawn but no matter what I do they always result in them turning into dead bushes. If it is the reverse and it needs to be planted BEFORE that timeframe then the book text is indeed wrong and needs to be fixed. It doesn't help that this is one of the first crops you make in this mod and that it's hard to progress if I can't get these started.

**Comment by teagan75** [comment]
I have this issue as well in version 0.2.1

**Comment by luke-bravenboer** [comment]
This ticket can be closed now, Cinderbella has been reworked since version 0.2.3 and now works correctly as per the new guidebook text (must be planted/grown between dusk and midnight only)
