### ISSUE TITLE
Book Images Offset On Larger Resolution

### ISSUE THREAD

**Issue by InsomniaKitten** [bafomdad/uniquecrops#2]
The images inside the book get offset weirdly when viewing at different screen resolutions.
Text seems to render correctly, however.

**Mod version:** [0.1.0](https://minecraft.curseforge.com/projects/unique-crops/files/2435404)
**Forge version:** [1.12-14.21.0.2331](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12-14.21.0.2331/forge-1.12-14.21.0.2331-changelog.txt)

1080p screen with Large GUI scale:

![](http://i.imgur.com/cJArC8t.png)
![](http://i.imgur.com/22RUO5U.png)

1080p screen with Normal GUI scale:

![](http://i.imgur.com/mWXz9KV.png)
![](http://i.imgur.com/LAbUGrU.png)

**Comment by jzburda** [comment]
I can also say that the book "Broke" but I don't know if I should make a seperate issue about it

http://i.imgur.com/olnQDQo.png

**Comment by bafomdad** [comment]
haha, that's weird

thanks for bringing this to my attention; something to stamp out while forge fixes other things in the meantime :]
