### ISSUE TITLE
Crash trying to open the debug pie chart

### ISSUE THREAD

**Issue by TheSaucyWelshman** [bafomdad/uniquecrops#21]
Custom pack on 1.12.2
https://pastebin.com/KrRzr0k3

Tested with minimal mods to confirm.
Unique Crops: 1.12.2-0.1.96
Forge: 14.23.5.2847
JEI: 4.15.0.292
https://pastebin.com/acUkaqn3

**Comment by ErnestoPeroPezzi** [comment]
I am also having this crash, please advise

**Comment by bafomdad** [comment]
advise trying to update unique crops to 0.1.97

**Comment by TheSaucyWelshman** [comment]
0.1.97 seems to have fixed the crash. Thank you!
