### ISSUE TITLE
[Issue] Hourglass of Nostalgia crafttweaker custom recipes ignore metadata

### ISSUE THREAD

**Issue by luke-bravenboer** [bafomdad/uniquecrops#22]
While adding some recipes for some of the currently-unobtainable Thaumcraft stone blocks via the new Hourglass of Nostalgia crafttweaker functionality, I noticed an issue where they don't take into account metadata- any block with a matching ID will be converted, regardless of metadata, causing JEI to display the recipe in a misleading way.

For example, this script here:
`HourglassConversion.addRecipe(<thaumcraft:stone_ancient_glyphed>, <extrautils2:decorativesolid:3>);`
... _should_ be using the Extra Utilities block 'Stoneburnt' as the input (which is '`decorativesolid:3`'), however instead the new recipe appears in JEI with the input as 'Border Stone' (which is actually '`decorativesolid:0`'):

![image](https://user-images.githubusercontent.com/3400211/72213124-30c29080-354e-11ea-86e9-a198aee7dc74.png)

Testing it out, it seems that the Hourglass is ignoring the metadata entirely, accepting _any_ block that matches `<extrautils2:decorativesolid:*>`:

![image](https://user-images.githubusercontent.com/3400211/72213141-6b2c2d80-354e-11ea-926a-0e34e110bde7.png)

**Comment by bafomdad** [comment]
try downloading the latest mod version and see if it works

**Comment by luke-bravenboer** [comment]
Can confirm metadata matching is now working as expected! Many thanks!
