### ISSUE TITLE
[Request] Make the Crafty Stalks table accept Unique Crops recipes

### ISSUE THREAD

**Issue by ErnestoPeroPezzi** [bafomdad/uniquecrops#23]
This seems like the logical thing to do; its basic enough that its not too far down, and provides an interesting way to make the unique crops crafting slightly easier.

While I'm here, could you also explain how to get impregnated leather, ruined blocks, and the music discs? Thanks!

**Comment by bafomdad** [comment]
Yeah, I've been sitting on making that a feature for a bit now, but don't see why not

The non glowy version of impregnated leather can be crafted normally. To get the glowy part, you have to charge up the former with crop power, which works the same way as it does with [this item](https://github.com/bafomdad/uniquecrops/wiki/Items#wildwood-staff)

Ruined blocks are part of world generation, generated deep underground at around 11y, in the overworld and in no ocean or deep ocean biomes.

Music discs can be randomly dropped from the crop that drops music discs

note to self: update the wiki more

**Comment by ErnestoPeroPezzi** [comment]
Here, I'll give you a list of everything I have no clue about so you don't have to because this mod is great and so are you:

Holiday Jellybeans
Blessed Seed
Dog Residue and Steve's Heart (they have entries but like ....)
Potion of Bordeom
Bunch of Diamonds
Flywood
Itero doesnt actually say what it does, just how to work it
And of course the other things we mentioned

Also some other issues I've found that I don't think deserve their own post;
-Battery beans don't actually do anything other than intake RF; I tried discharging them in many mods 
     energy storage yet it didn't work. They are an amazing and very unique way of RF generation, 
     shame they dont actually work as of now.
-Itero does not seem to work, right clicking does nothing, adding more pressure plates does nothing 
     (I dont have any right click to harvest mods active either)
-Exedo also doesnt seem to work, just sits there
-Is there a point in adding ruined blocks to worldgen? An appeal for this mod is the total lack of worldgen it adds, adding one bit of generation when you can make them obtainable with an exisitng mechanic (cough hourglass cough) seem a bit messy
-The dimension hooboy. I absolutely love the concept, and how you have to use alot of things from the mod to get around in there. My issues are 1: right clicking doesnt work in the dimension, and 2: thats its hideous; the ghost blocks spread out like that look horrible, the fog changes colours jarringly, the skybox is bright blue, etc. Making the ghost blocks clumps of clouds or whatnot and fixing the fig would go a long way

Thanks for making this mod and keep up the good work :)

**Comment by bafomdad** [comment]
thanks for the wiki work suggestions! Some of them have been left undocumented on purpose; their uses can explain themselves or be discovered in the game. Flywood is endemic to the crop world dimension, and as such is only aesthetic purposes.

rightclicking being restricted in the dimension is one of many things I did to make sure many of the blocks couldn't be moved around. You can still open the loot chests that generate, of course. The fog and colors are indeed a problem, so will have to work on that. The ghost blocks are there to be made solid by yourselves, if a path to the loot chest islands seems impossible. I agree that it can still look better.

- battery beans should be fixed. I tested with actually additions' energizer and ennervator blocks to confirm
- if the itero crops don't work, try deleting the _uniquecrops_ folder in your instance directory; a recipe tweak was changed to the creation of the itero block. the mod will recreate the directory with the new default recipes.
- exedo should work. I've just tested this on a dedicated server and they ate up llamas and chickens, no problem. They just don't happen immediately, as expected. It also helps to keep mobs on the same level as the plant
- the ruins world generation is there as an optional feature, to help hint players at the existence of a portal to another dimension. a config option will be added to disable this. a crafttweaker recipe can use any of the many recipe features of the mod to add the ruined blocks to them if you wish

**Comment by ErnestoPeroPezzi** [comment]
Thanks for listening :)
