### ISSUE TITLE
[Issue][0.1.99] Overcharged Battery Beans

### ISSUE THREAD

**Issue by luke-bravenboer** [bafomdad/uniquecrops#25]
With the change to battery beans in the 0.1.99 update, every Power/Industria crop that's harvested gives a bean with a charge of 100,000, regardless of their maximum capacity, causing major UI issues with minecraft's 'damage indicator' bar:
![2020-01-17_10 36 52](https://user-images.githubusercontent.com/3400211/72565376-93cd7200-3916-11ea-81ce-8633e2102e79.png)

This might be better suited for a separate ticket, but I think it's relevant:
I personally would like to adjust either the growth rate of these crops, the max capacity of the beans, and/or the chance of bonus seeds on harvest, as I think they're a bit too powerful now (at least for my personal modpack). They take about 88 seconds to absorb 100k RF, giving them a generation rate of ~56 RF/t. decent enough on its own; but since that's _per crop_, and they producing additional seeds on harvest, it won't take long to get a whole field of infinite energy, for the cost of only a single industria seed.
Of course, you'd still need to extract the energy out of each bean, and this is obviously assuming that they're all of the '100k' variety, but compared to other 'solar panels'- and particularly due to the fact that the crop's self-replicating- I'd still prefer to adjust this crop than disabling it outright :)

**Comment by bafomdad** [comment]
yeah, that's pretty silly. I thought I capped that value already, hmm.

I do believe that is a valid balance concern, will have to address both of these issues in the next patch :]

**Comment by luke-bravenboer** [comment]
Confirmed fixed in latest version
