### ISSUE TITLE
Issues with Cinderbella

### ISSUE THREAD

**Issue by cinniebuns** [bafomdad/uniquecrops#35]
Hello, I am new to using the Unique Crops and I'm using it through a R.A.D. server that my brother runs. I just got done with getting my Artisia seeds and having them grow, and now I have my Cinderbella shoots, but unfortunately I am unable to grow them to farm more, instead of crafting them on my Artisias. It happened to be a method I use, but it's a pretty tedious one.
I've looked on YouTube to be sure I was doing the right things to help Cinder grow, but to no avail. She withers away anyway. 
So, I'll go to put my 4 pumpkins down and plot a little farmland, and in the daytime if I add water from my waterbucket to feed her, she withers away. With the bonemeal, she does not grow. If I do plant her at night and try to water her, she withers away still. Bonemeal and water does nothing. I looked through the guide and it states: " They must be planted between midnight and dawn," but I cannot plant her at those times. 
Hopefully it gets resolved because I really look forward to this mod. 
![cinderbella](https://user-images.githubusercontent.com/68677834/88253831-40e7c500-cc81-11ea-8a84-a61643a1acca.PNG)

**Comment by luke-bravenboer** [comment]
Also confirming that the Cinderbella crop is currently not growing at all in v0.2.2, at any time of day.

Bone Meal causes it to wilt as well (and it does say "_Can Bonemeal: true_" in the book)

**Comment by luke-bravenboer** [comment]
Confirming that the Cinderbella crop now grows correctly as per the new guidebook text (only from dusk - midnight).
