### ISSUE TITLE
Abstract Seeds visual glitch & are now producing Wheat as a by-product

### ISSUE THREAD

**Issue by luke-bravenboer** [bafomdad/uniquecrops#39]
In previous versions of Unique Crops, 'Abstract' crops wouldn't appear in the world at all (as expected from their description in the guide book).

However since version 0.2.1, they now appear in-world as an actual crop:

![2021-01-07_11 39 31](https://user-images.githubusercontent.com/3400211/103827160-36a96e00-50dd-11eb-8d11-a8938a141f4b.png)

... on top of that, we can also now use bone meal to grow the crop, which produces... wheat? And breaking the crop gives me wheat seeds:

![2021-01-07_11 41 39](https://user-images.githubusercontent.com/3400211/103827280-812aea80-50dd-11eb-8197-9a1490cac9f3.png)

**Comment by bafomdad** [comment]
oh, huh

normally you're not able to physically plant that crop into the world, but due to some refactoring I overlooked this crop's special behavior

**Comment by luke-bravenboer** [comment]
I guess you could say you... abstracted too much of the class?

...I'll see myself out.

**Comment by luke-bravenboer** [comment]
@bafomdad Since this fix, the Abstract seeds aren't being consumed when I right-click them onto tilled dirt (in survival mode)- is this intentional?
I am getting the residue so it is still 'growing', it's just not using up any of the seeds.
