### ISSUE TITLE
Will an Abstract ever spawn?

### ISSUE THREAD

**Issue by krwminer** [bafomdad/uniquecrops#4]
The only place I see that Abstract can be created is through onPlayerTick(), is that right?

If so, (which I might have missed something), then I think that it will never be created.
On line 469 of UCEventHandlerServer.java it returns if there was no key for TAG_ABSTRACT.
Shouldn't that be the reverse, return if there was was a key for TAG_ABSTRACT?

**Comment by bafomdad** [comment]
Yes, that should be correct. During my initial testings, the abstract seed spawned in my inventory just a little too quickly, so I believe the only thing I changed in the code after that was increasing the amount of time and randomness to it.

Since I always second guess myself on stuff like this, I'll take another look into it. Thanks for the heads up :]

**Comment by krwminer** [comment]
I just do not see how the TAG_ABSTRACT is set without planting an Abstract seed. Since it returns from the Tick if there was no tag found, how can TAG_ABSTRACT ever be set? Is it possible you planted a seed before you tested this? Or am I just plain missing something big here? Thanks for looking into it. :)

**Comment by bafomdad** [comment]
Ok, having taken a look at it, this definitely gets set when you plant an abstract seed. I tweaked the code while I was in there since some of it looked odd to me, but after testing it, it all should work.

**Comment by krwminer** [comment]
OK, I will bite then... How do you go about getting an abstract seed?

**Comment by bafomdad** [comment]
if you mean making one seed, you can craft it using the seed crafting recipe.

if you mean getting the crop it gives, just planting one will mean that at some point it will randomly give an abstract residue, plus a chance of giving an extra later on before considering it fully "harvested", requiring a replanting.

**Comment by krwminer** [comment]
Wow. I can't believe how I missed that. The minecraft crafting recipe came up by default so I missed the seed crafting recipe. D'oh! Thank you for being patient with me. I love your mod!
