### ISSUE TITLE
[1.18.2] java.lang.NullPointerException: Cannot invoke "net.minecraft.client.multiplayer.ClientLevel.m_7465_()" because "mc.f_91073_" is null

### ISSUE THREAD

**Issue by PhweeDev** [bafomdad/uniquecrops#65]
Hello,

I've been playing on a massive 1.18.2 skyblock survival. but when adding 0.1.27 to my pack. I would get the following crash report when joining world. It also does the same thing when creating a new world. Can you look into this? From the report, I suspect FastSuite, DPAnvil, or ElementalCraft.

Report:  https://paste.gg/p/anonymous/31ed3ba7f50242acb43e2132ec2e7515

Log: https://paste.gg/p/anonymous/2c02d09b2f6a4a0bb2b41d02dc012e71

**Comment by bafomdad** [comment]
huh, interesting mod interaction.

I was able to reproduce this issue easily with elemental craft and possibly dpanvil, one of those two. fastsuite wasn't able to cause the crash, so that gets ruled out.

anyway, I've released an update with a hotfix for this one. let me know how it goes

**Comment by PhweeDev** [comment]
It appears that bug has been fixed! ....however. I found another one. It has to do with the UniqueCrops'"Zombification" potion. It appears it may be an issue between It Shall Not Tick and/or\ AdPother (Pollution of the Realms)

https://paste.gg/p/anonymous/9c166f119d9449dfb845c36bd315228b

**Comment by bafomdad** [comment]
good to know it's been fixed!

ah, thanks for trying out the zombie potion :smile: that's another easy fix, though I do not know why the potion effects would be null in a potion >remove< event..

**Comment by PhweeDev** [comment]
Ironically I didn't even try it. Right before my world said "joining world", It crashed with that.

**Comment by PhweeDev** [comment]
Using a compiled build after your commits. My world now works well. No crashes preventing me from playing. Thanks!
