### ISSUE TITLE
questions concerning some crops/blocks/items

### ISSUE THREAD

**Issue by Deing-Young** [bafomdad/uniquecrops#7]
Version: uniquecrops-1.10.2-0.2.02
1. After a feroxia seed is planted, no new pages can be found on the guide book thus I have no idea of the demands of those plants, how exactly to make them grow and how to get more information?

2. I read on the wiki you can use a Ender snooker on the dark blocks to pick them up, but I just couldn't achieve it, shift/non-shift left click/right click all have no effect. So is it only possible to obtain these blocks by dropping an Enderman there (without changing the gamerule)? But it may take ages before Endermen take any particular interest on those blocks...

3. Right clicking bone meal on air or non-plant blocks will instantly turn them into edible lapis, is this intended or bug? This create a way to make lapis out of bones since the edible lapis are in "ore lapis" and can be used in some crafting, which is too imbalance..   BTW, how to obtain other edible materials?

4. The scienticia plants only eat letters on the first page of the written books, is this intended or a bug?

This really seems to be an extraordinary mod, love it on first sight, but I am much troubled by these problems so I do hope that someone could help me out.

**Comment by bafomdad** [comment]
hello

1. I believe it should add a page in the book as the very last page for the growth entry. If it doesn't do that, then I would like to find a way to reliably reproduce that effect. Also, it may simply take just reopening the book to make the page appear.

2. That feature is only available on the newer versions for 1.12. In older versions, Dark Blocks can be moveable above 10y. 10y and below they are unmoveable, like bedrock, but tools from other mods may be able to pick it up

3. This is unintended. I notice that I didn't do a check for dye damage in older versions, and the check has been added in the newer versions. The currently convertible edible materials to right click with are iron/gold/diamond/emerald and lapis

4. this is a bug. there are quite a few things like this one I've found in my own mod that I want to make better at some point. just simply getting things working, EG: getting the bookplant to eat letters out of the book, were the priority to get things up and working first.

**Comment by Deing-Young** [comment]
Thanks a lot for replying so soon~
I rechecked about feroxia today and this time there is a new page. No idea why it failed yesterday (I did reopen a new book), but if it happens again, I'll try to find out more about it.
Again many thanks for creating this interesting mod.
