### ISSUE TITLE
[1.12.2] CraftTweaker recipe support

### ISSUE THREAD

**Issue by codetaylor** [bafomdad/uniquecrops#8]
This is a great mod! The crops are weird AF and I love it! :)

I want to integrate this into my magic based modpack that I'm working on and I was wondering if you would be open to a PR that refactors the recipe registration system slightly to accommodate CraftTweaker integration?

I'm happy to do the work, but I would like your take on the idea before I actually do the work.

The PR would not introduce any hard dependencies to the mod, but would of course introduce a compile time dependency on CT in the gradle build script.

**Comment by bafomdad** [comment]
if you mean to add CraftTweaker support for the seed recipes, then I'm open to a PR for the 1.12 branch. that's the version I wish to actively work on from here on out

it's a nice idea, I'm glad you like my mod so far :]

**Comment by codetaylor** [comment]
Alright, I'm working on getting all the dependencies set up in the build file:

```
dependencies {
    // CraftTweaker
    deobfCompile "CraftTweaker2:CraftTweaker2-MC1120-Main:1.12-4.0.10.+"
    deobfCompile "CraftTweaker2:CraftTweaker2-API:4.0.10.+"
    deobfCompile "CraftTweaker2:ZenScript:4.0.10.+"
    deobfCompile "com.blamejared:MTLib:3.0.+"

    // JEI
    deobfCompile "mezz.jei:jei_1.12.2:4.8.0.+"

    // Baubles
    deobfCompile "com.azanor.baubles:Baubles:1.12-1.5.2"

    // Immersive Engineering
    compile name: "ImmersiveEngineering-0.12-67-177-deobf"
}
```

But I seem to be missing the `com.bafomdad.uniquecrops.api` package and I can't seem to find it anywhere. Is it a local dependency that you haven't published?

It looks like it contains classes such as `ICropBook` and `IBookUpgradeable` and such...

I think that's the last thing I need to get it to compile.

**Comment by bafomdad** [comment]
huh, it isn't really an API package. It's just an internal folder that doesn't really reach outside of the whole mod.

looking at the 1.12 branch copy on here, it is somehow missing. it might have gotten added to gitignore by accident. this has been fixed now

**Comment by codetaylor** [comment]
Thanks! I've restructured the 1.12 branch to follow Gradle convention and made a build.gradle with the necessary dependencies. It pulls all dependencies via Maven with the exception of IE: it just uses the local copy of IE.

I'm now able to build and run the project. Next step, CT integration! :D

You can view my progress here:
https://github.com/codetaylor/uniquecrops/tree/1.12

**Comment by bafomdad** [comment]
alright, great!

I'm now intrigued by the CraftTweaker integration stuff, so I may give this a whirl myself sometime..
